http:
  port: "8081"
 
db: 
  sfc:
    accountname: "HKBLQNP-DF08692"
    warehouse: "COMPUTE_WH"
    database: "VITECH"
    schema: "BFS"
    user: "RENUKASRINIVAS"
    password: "Renu@123456789"
    role: "ACCOUNTADMIN"
    
email:
  config:
    host: "smtp.gmail.com"
    port: "587"
    user: "renukamithun2310@gmail.com"
    password: "jawjyobogdouxgxf"
    
deployment:
    app:
      runtime: "4.11.0"
    region: "us-east-2"
    workers: "1"
    workerType: "MICRO"
    
 